### ISSUE TITLE
Warnings silenciosas en la action de fix-code

### ISSUE THREAD

**Issue by mauriciopasquier** [muadev/tendercats#33]
Tenemos un problema con nuestra acción de lint, porque estas warnings deberían aparecer como algo a corregir en el pull request:

![image](https://user-images.githubusercontent.com/142792/149220213-5cc8cc5d-f689-42da-9588-dd16772181a2.png)

Tal vez se pueda hacer que salgan como errores, o algo así.

**Comment by tesitura** [comment]
Yo creo que si hacemos que las Warnings den error en el Action va a sumar mucho ruido y nos va a diluir la criticidad de Errores más graves. Creo que está bien que la Warning quede como una línea optativa a tener en cuenta. En última instancia si creemos que una Warning es crítica adecuaría la config de `eslint` para que sea reconocida como error.

**Comment by mauriciopasquier** [comment]
A mí me parece que al menos estas warnings son muy importantes a resolver para la calidad del código. No son graves en el sentido de que no crashean la app, pero no deberíamos estar mergeando así, y sin que salga el error en el pull request nunca nos enteraríamos.

Otra opción es hacer lo de los hooks locales que decidimos no hacer porque delegamos a la Action.

**Comment by mauriciopasquier** [comment]
Dejo [esta cita](https://github.com/eslint/eslint/issues/2309#issuecomment-219828044) por las dudas que nos sirva:

> `--max-warnings=0` means that any warnings cause eslint to report an error.

**Comment by mauriciopasquier** [comment]
Los warnings quedan como comentarios de review, y además decidimos escalar cada warning individual.
